import type { Metadata } from 'next'
import '@/styles/global.scss'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/antDesign/AntRegistry';
import ReduxProvider from '@/redux/Provider';
import Header from '@/components/Header';
import { ConfigProvider } from 'antd';
import theme from '@/antDesign/ThemeConfig'
import CheckAuth from '@/components/checkAuth'
import { $axios } from '@/axios/config';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Магазин на Next-js',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const getUser = async()=> {
    try {
      const {data} = await $axios.get('http://localhost:1337/api/users/me')

      //  console.log(data)
       return data 
    } catch(error) {
      console.error(error);
      return null
    }

  }

 
   const user = await getUser()
let isAuth: boolean = false

   if(user) {
    isAuth = true
   }

  return (
    <html lang="en">
      <body className={inter.className}>
       <ReduxProvider>
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
        <Header isAuth={isAuth} />
        {children}
        </ConfigProvider>
      </StyledComponentsRegistry>
       </ReduxProvider>
      </body>
    </html>
  )
}
