import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/AntRegistry';
import ReduxProvider from '@/redux/Provider';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <ReduxProvider>
      <StyledComponentsRegistry>
        <Header/>
        {children}
      </StyledComponentsRegistry>
       </ReduxProvider>
      </body>
    </html>
  )
}
